services:
  openvpn-client:
    image: jesusdf/docker-strongswan:latest
    container_name: docker-strongswan
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ./config/ipsec.conf:/etc/ipsec.conf
      - ./config/ipsec.d:/etc/ipsec.d
      - ./config/ipsec.secrets:/etc/ipsec.secrets
      - ./config/strongswan.conf:/etc/strongswan.conf
      - ./config/swanctl:/etc/swanctl
    restart: unless-stopped