services:
  openvpn-client:
    image: jesusdf/docker-strongswan:latest
    container_name: docker-strongswan
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./config/strongswan.conf:/etc/strongswan.conf
      - ./config/swanctl:/etc/swanctl
    restart: unless-stopped
