charon {
  send_vendor_id = no
  retry_initiate_interval = 30
  retransmit_tries   = 5
  retransmit_timeout = 4.0
  retransmit_base    = 1.8
  plugins {
    eap-dynamic {
      preferred = mschapv2, tls, md5
    }
    dhcp {
      identity_lease = yes
    }
  }
  filelog {
    stderr {
      #default = 3
      flush_line = yes
    }
  }
}
